// swift-tools-version:5.9
import PackageDescription

let package = Package(
    name: "pesterm",
    platforms: [
        .macOS(.v11) // Big Sur — see Constants table (§4 gotcha #1 is a Big Sur behavior)
    ],
    dependencies: [
        // The ONE allowed compile-time external dependency (lean footprint posture).
        .package(url: "https://github.com/apple/swift-argument-parser", from: "1.3.0")
    ],
    targets: [
        // Regular SwiftPM C target (NOT a systemLibrary target) wrapping the in-tree,
        // generated iTerm2 ScriptingBridge header. The CITermBridge module is
        // AUTO-GENERATED by SwiftPM from the single umbrella header in include/.
        .target(
            name: "CITermBridge",
            path: "Sources/CITermBridge",
            publicHeadersPath: "include",
            // The pesterm-added probe functions carry honest `_Nullable` returns, which
            // makes clang demand nullability on EVERY pointer in the header
            // (-Wnullability-completeness). PRIMARY suppression is the in-header pragma
            // (the only thing Swift's ClangImporter also parses — these flags don't reach
            // it); this flag is the regen-proof backstop for the C-target compile, since
            // verify-sdef.sh's blind cp clobbers the in-header pragma.
            cSettings: [
                .unsafeFlags(["-Wno-nullability-completeness"])
            ]
        ),
        // Same shape for the Ghostty ScriptingBridge header (vendored, generated from
        // Ghostty 1.3.1's sdef — see docs/ghostty-sdef-findings.md).
        .target(
            name: "CGhosttyBridge",
            path: "Sources/CGhosttyBridge",
            publicHeadersPath: "include",
            // Same rationale as CITermBridge: in-header pragma is primary (reaches the
            // ClangImporter); this flag backstops the C compile across regenerations.
            cSettings: [
                .unsafeFlags(["-Wno-nullability-completeness"])
            ]
        ),
        .executableTarget(
            name: "pesterm",
            dependencies: [
                "CITermBridge",
                "CGhosttyBridge",
                .product(name: "ArgumentParser", package: "swift-argument-parser")
            ],
            path: "Sources/pesterm",
            // CLAUDE.md guidance files live beside the code they document; they are docs,
            // not build inputs, so exclude them or SwiftPM flags them as stray resources.
            exclude: [
                "Adapters/CLAUDE.md",
                "Permission/CLAUDE.md",
                "Wiring/CLAUDE.md",
            ],
            // The generated header references ScriptingBridge types, so the consuming
            // target must link the framework explicitly. AppKit/Foundation for
            // activation + Foundation APIs.
            linkerSettings: [
                .linkedFramework("ScriptingBridge"),
                .linkedFramework("AppKit"),
                .linkedFramework("Foundation")
            ]
        ),
        .testTarget(
            name: "pestermTests",
            dependencies: ["pesterm"],
            path: "Tests/pestermTests"
        )
    ]
)
